In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.io as spio

In [2]:
#导入matlab格式文件
data =spio.loadmat('ex3data1.mat')
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [3]:
#可以看出data代表dict字典数据类型，字典是Python中唯一内建的映射类
# X 和 y都是数组
data['X'].shape, data['y'].shape#要同时显示，记得打逗号

((5000, 400), (5000, 1))

In [4]:
#测试shape在数组和矩阵中区别
#data['X'].shape[0]#5000  ,在数组中返回行
#X_Matrix = np.matrix(data['X'])
#X_Matrix.shape[0]#5000 也是返回行
#len(X_Matrix)

In [5]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [6]:
#测试下sigmoid函数
sigmoid(0)

0.5

In [7]:
#编写代价函数
def cost(theta , X  ,y , learnRate):
    X = np.matrix(X)
    y = np.matrix(y)
    theta = np.matrix(theta)
    #记住在深度学习中一般字母表示都是列向量，但是在python中都是创建的行向量
    first = np.multiply(y, np.log(sigmoid(X*theta.T)) )#X中每一行是一个样本
    second = np.multiply(1-y, np.log(1-sigmoid(X*theta.T)) )
    reg = learnRate * np.sum(np.power(theta[: , 1: theta.shape[1] ] , 2  ))/(2*len(X))
    return np.sum(-first - second)/len(X) +reg

In [8]:
#梯度下降法就是来求使代价函数最小的theta取值
#这是求梯度，不是梯度下降
def grad_loop(theta , X , y , learnRate):
    X = np.matrix(X)
    y = np.matrix(y)
    theta = np.matrix(theta)
    #判断有多少theta有多少个，也就是循环多少次
    parameters = theta.shape[1]
    #构建一个数组用来存储梯度
    for j in range(parameters):
        if j ==0:
            grad[j] = np.sum( np.mulitiply( sigmid(X*theta.T) - y   , X[ : , j ] )) / len(X)
        else:
            #theta是一维数组，转换为行向量
            grad[j] = np.sum( np.mulitiply( sigmid(X*theta.T) - y   , X[ : , j ] )) / len(X) +learnRate*theta[: , j]/len(X)
    return grad;  

#测试 theta[j] 与 theta[; , j]

In [9]:
#向量化
def grad(theta , X , y , learnRate):#X是5000，401   ， y是5000 ， 1  ，theta是 1，401
    X = np.matrix(X)#可以不用转矩阵，数组中一样可以运算。matrix可以用*来进行矩阵运算
    y = np.matrix(y)
    theta = np.matrix(theta)
    parameters = theta.shape[1]
    error = sigmoid(X*theta.T) - y #是一个(5000,1)的矩阵
    #(X.T * error) 对应位置点乘然后按列相加  ,也就是X.T为 401，5000的矩阵，返回的是401，1的矩阵
    #经过测试 np.mulitiply(errot , X)返回的是一个 5000，401的矩阵
    grad =np.sum(np.multiply(error , X) , 0 ) /len(X) + learnRate*theta/len(X)# 测试返回1,401
    grad[0,0] = np.sum(np.multiply(error , X[:,0]) , 0 ) /len(X) #返回的就是1个数，赋给了矩阵中第1个
    return np.array(grad).ravel() 

测试 error = sigmid(X*theta.T)是数组还是列表，列表不具有数组的一些属性
慢点想，追求懂，不追求进度
仔细思考下向量化的含义
结合下面表达式，可以看出来梯度，也就是后面不带a的部分， 有部分是不变的，类似于 
A[x1 ,x2 ,... xj]+B[theta1,theta2...thetaj]




\begin{align}
  & Repeat\text{ }until\text{ }convergence\text{ }\!\!\{\!\!\text{ } \\ 
 & \text{     }{{\theta }_{0}}:={{\theta }_{0}}-a\frac{1}{m}\sum\limits_{i=1}^{m}{[{{h}_{\theta }}\left( {{x}^{(i)}} \right)-{{y}^{(i)}}]x_{_{0}}^{(i)}} \\ 
 & \text{     }{{\theta }_{j}}:={{\theta }_{j}}-a\frac{1}{m}\sum\limits_{i=1}^{m}{[{{h}_{\theta }}\left( {{x}^{(i)}} \right)-{{y}^{(i)}}]x_{j}^{(i)}}+\frac{\lambda }{m}{{\theta }_{j}} \\ 
 & \text{          }\!\!\}\!\!\text{ } \\ 
 & Repeat \\ 
\end{align}

以下是原始代码是使用for循环的梯度函数：

In [10]:
#求证error
#x0=np.zeros(data['X'].shape[0])
#X = np.insert(data['X'] , 0 , values=x0 , axis = 1)
#X.shape
#theta = np.zeros(X.shape[1])
#X = np.matrix(X)
#theta = np.matrix(theta)
#sigmoid(X*theta.T)
#经过测试sigmoid返回的是矩阵

测试np.insert插入多维数组
x0 = np.zeros( (2, data['X'].shape[1] )  )
x0
X1 = np.insert(data['X'] , 0 , values=x0 , axis = 1)
X1.shape

y=data['y']
error = sigmoid(X*theta.T) - y
grad=np.sum(np.multiply(error , X) , 1)
error.shape
m=np.multiply(error , X)
m.shape

In [11]:
from scipy.optimize import minimize

def one_vs_all(X, y, num_labels, learning_rate):
    rows = X.shape[0]#样本数
    params = X.shape[1]#特征数
    '''
    # k X (n + 1) array for the parameters of each of the k classifiers
    #后面部分翻译：每个k分类器的参数数组
    ''' 
    all_theta = np.zeros((num_labels, params + 1))#个人认为是每一个分类器的theta
    
    # 添加x0=1
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    

    '''
    range（起始位置 默认0，结束位置，步长 默认1） 返回的是list列表
    这里返回的是 [1 2....num_labels]
    '''
    for i in range(1, num_labels + 1):
        theta = np.zeros(params + 1)
        '''
        for x in y    x依次表示y中的每一个元素，遍历完所有元素循环结束。
        这里的y是 1到10，看上面y的输出
        '''
        y_i = np.array([1 if label == i else 0 for label in y])
        y_i = np.reshape(y_i, (rows, 1))
        
        '''
        x0是变量的初始猜测值，cost函数的变量是theta
        args是传递给fun中的额外参数，fun中没有常数项，所以需要传入额外参数
        method是求极值的方法
        jac是梯度函数
        res返回结果，其中x是返回的解决数组
        '''
        fmin = minimize(fun=cost, x0=theta, args=(X, y_i, learning_rate), method='TNC', jac=grad)
        '''
        假设 i = 5，y_5中如果是1表示这个值是5，cost是一个逻辑回归的代价函数
        注意这是训练集，是来得出theta值的
        这是去一个theta来使cost最小，记住逻辑回归的代价函数包含了两种情况
        这里你不要想着是来预测y的，而是已知y来训练theta
        每一个结果都有一个分类器
        '''
        all_theta[i-1,:] = fmin.x
    
    return all_theta

In [12]:
'''
#对于一维数组或者列表，unique函数去除其中重复的元素，
#并按元素由大到小返回一个新的无元素重复的元组或者列表
'''
np.unique(data['y'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [13]:
all_theta = one_vs_all(data['X'],data['y'],10 , 1)
all_theta

array([[-2.38279424e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.30454494e-03, -7.79470247e-10,  0.00000000e+00],
       [-3.18625271e+00,  0.00000000e+00,  0.00000000e+00, ...,
         4.45623736e-03, -5.08059731e-04,  0.00000000e+00],
       [-4.80017880e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -2.86880533e-05, -2.46881018e-07,  0.00000000e+00],
       ...,
       [-7.98458958e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -8.94979804e-05,  7.22088504e-06,  0.00000000e+00],
       [-4.57182022e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.33402586e-03,  9.97117351e-05,  0.00000000e+00],
       [-5.40483896e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -1.16620262e-04,  7.88267408e-06,  0.00000000e+00]])

In [14]:
all_theta.shape

(10, 401)

In [52]:
def predict_all(X,theta):
    x0=np.ones(data['X'].shape[0])
    X = np.insert(X, 0 , values=x0 , axis = 1)
    X = np.matrix(X)
    theta = np.matrix(theta) 
    all_result = np.array( sigmoid(X* theta.T) )
    return np.argmax(all_result , axis = 1)+1;
predict_result= predict_all(data['X'], all_theta)  
#result.shape   
predict_result   


array([10, 10, 10, ...,  9,  9,  7], dtype=int64)

In [55]:
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, data['y'])]#correct是列表
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))

accuracy = 94.46%


5000