In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.arange(4)
print(a ,b)

[1 2 3 4] [0 1 2 3]


In [2]:
print(b)

[0 1 2 3]


In [3]:
print(a+b)

[1 3 5 7]


In [4]:
print(a*b)#对应位相乘

[ 0  2  6 12]


In [5]:
d = a.dot(b)
print(d)

20


In [7]:
e = np.random.random((2,3,4))#随机生成一个数组在值在0~1内

In [8]:
print(e)

[[[0.63636831 0.77011094 0.0388694  0.3098374 ]
  [0.53848984 0.17645626 0.55305699 0.49209667]
  [0.84279172 0.13227696 0.14010659 0.44783998]]

 [[0.88804063 0.18157696 0.2181207  0.96631935]
  [0.48086031 0.60590359 0.18967629 0.47878398]
  [0.09995171 0.09363388 0.81578352 0.29875881]]]


In [10]:
f = np.random.random((2,3))
print(f)

[[0.29300487 0.89746251 0.21762603]
 [0.58968699 0.93784622 0.63809175]]


In [11]:
g = f.ndim#返回行数
print(g)

2


In [12]:
h = np.empty((2,4))
print(h)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.98807563e-321 1.69119330e-306 1.78020983e-306]]


In [13]:
print(h.size)

8


In [15]:
g = np.array([[1,2,3],[4,5,6]])
g_sum = np.sum(g , 1)#按行相加
print(g_sum)
g_min = np.min(g , 0)#列最小
print(g_min)
#同理最大值

[ 6 15]
[1 2 3]


In [46]:
g1 = np.array([[5,5,5],[3,2,7]])

In [24]:
h = np.argmin(g1,0)
#numpy.argmin(a, axis=None, out=None) 
#返回axis方向上最小值下表，默认将输入数组展平
print(h)

[1 1 0]


In [25]:
i = np.mean(g)#默认展平，同上
print(i)

3.5


In [27]:
print(np.median(g,1))

[2. 5.]


In [28]:
print(np.cumsum(g,1))

[[ 1  3  6]
 [ 4  9 15]]


In [33]:
print(np.diff(g))

[[1 1]
 [1 1]]


In [34]:
print(np.nonzero(g))

(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))


In [58]:
h = np.array([[3,2], [1,2]])

In [63]:
h1=np.sort(h ,0)
print(h1)

[[1 2]
 [3 2]]


In [65]:
h2=np.clip(h,1,2)
h2

array([[2, 2],
       [1, 2]])